# 01-deploy-vault

- name: helm diff plugin
  kubernetes.core.helm_plugin:
    state: present
    plugin_path: https://github.com/databus23/helm-diff

- name: add helm chart repos
  kubernetes.core.helm_repository:
    state: present
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: deploy vault
  kubernetes.core.helm:
    state: present
    release_name: "{{ vault.name }}"
    release_namespace: "{{ vault.namespace }}"
    create_namespace: "{{ vault.create_namespace }}"
    chart_ref: hashicorp/vault
    release_values: "{{ lookup('template', vaultValuesLocation) | from_yaml }}"

- name: deploy consul
  kubernetes.core.helm:
    state: present
    release_name: "{{ vault.name }}-db"
    release_namespace: "{{ vault.namespace }}"
    create_namespace: "{{ vault.create_namespace }}"
    chart_ref: hashicorp/consul
    release_values: "{{ lookup('template', consulValuesLocation) | from_yaml }}"
    wait: yes