

# location of the kubeconfig file for the target cluster on the localhost machine
kubeconfig: ~/.kube/config

# where the vault root credentials should be saved
cluster_keys.json:
  destination: "~/Development/vault-test/ansible/cluster-keys.json"


vault:
  address: "http://127.0.0.1:8200"
